apiVersion: v1
kind: ConfigMap
data:
  YARN_PRODUCTION: {{ .Values.environment.yarn_production | quote }}
  YARN_RUNTIME: {{ .Values.environment.yarn_runtime | quote }}
metadata:
  name: {{ .Release.Name }}-configmap